[package]
name = "cyclebox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = { version = "1.0.6" }
roaring = { version = "0.10.0" }